server:
  port: 8080

spring:
  application:
    name: money-calculator
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: ${DB_DRIVER:oracle.jdbc.OracleDriver}
    url: ${DATABASE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
    username: ${DB_USERNAME:calc}
    password: ${DB_PASSWORD:calc1234}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:}

  
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.ajaajas.calc: DEBUG
    root: INFO

debug: false