server:
  port: 8080

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: money-calculator
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.ajaajas.calc: DEBUG
    root: INFO