server:
  port: 8080

spring:
  application:
    name: money-calculator
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: namingcenter
    password: java1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.ajaajas.calc: DEBUG
    root: INFO

debug: false